version: '3.9'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://chronouser:chronopass@db/chronoserve
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chronouser
      POSTGRES_PASSWORD: chronopass
      POSTGRES_DB: chronoserve
    volumes:
      - pgdata:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  service1:
    build: ./service1
    ports:
      - "8001:8001"


volumes:
  pgdata:
